name: tag build and publish image

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            simojenki/meshcommander
          tags: |
            type=semver,pattern={{version}}
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            MESHCOMMANDER_VERSION=${{ steps.meta.outputs.tags }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags || '***/meshcommander:latest' }}
          labels: ${{ steps.meta.outputs.labels }}